### ISSUE TITLE
Functions School Ideas by snøhetta

### ISSUE THREAD

**Issue by functionalflow** [functionalflow/brains#1917]
![0thctai1ol8gempw](https://user-images.githubusercontent.com/3938314/40347049-6a533e86-5dd1-11e8-8c7a-5f6883d9e281.jpg)

![ncm8s1dtzj5afsuz](https://user-images.githubusercontent.com/3938314/40347077-83bbb5d8-5dd1-11e8-9f43-e0c7e1be39f3.jpg)

![screen shot 2018-05-22 at 1 03 14 pm](https://user-images.githubusercontent.com/3938314/40347103-92da923c-5dd1-11e8-8758-a1633c6a14b0.png)

![snohetta under 1](https://user-images.githubusercontent.com/3938314/40347091-8aaa26cc-5dd1-11e8-876e-6c900ba02566.jpg)

**Comment by allenleein** [comment]
I think one of the modern EDU problem is not modern enough. 

We are so struck in an old system just because some people are comfortable with. 

EDU put too much value on materialistic things. Having seems to be much important than being.
